# Define

In [3]:
import numpy
matrix = numpy.arange(36).reshape(6, 6)
print matrix

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


# Matrix Transpose

In [6]:
# matrix transpose
zip(*matrix)

[(0, 6, 12, 18, 24, 30),
 (1, 7, 13, 19, 25, 31),
 (2, 8, 14, 20, 26, 32),
 (3, 9, 15, 21, 27, 33),
 (4, 10, 16, 22, 28, 34),
 (5, 11, 17, 23, 29, 35)]

# Sum of Row & Column 

In [7]:
# sum of rows
row_sum = []
for row in matrix:
    row_sum.append(sum(row))

print row_sum

# sum of columns
col_sum = []
for col in zip(*matrix):
  col_sum.append(sum(col))

print col_sum

[15, 51, 87, 123, 159, 195]
[90, 96, 102, 108, 114, 120]


# Matrix Rotation

In [22]:
# rotate clockwise
zip(*matrix[::-1])

[(30, 24, 18, 12, 6, 0),
 (31, 25, 19, 13, 7, 1),
 (32, 26, 20, 14, 8, 2),
 (33, 27, 21, 15, 9, 3),
 (34, 28, 22, 16, 10, 4),
 (35, 29, 23, 17, 11, 5)]

In [24]:
# rotate counterclockwise
zip(*matrix)[::-1]

[(5, 11, 17, 23, 29, 35),
 (4, 10, 16, 22, 28, 34),
 (3, 9, 15, 21, 27, 33),
 (2, 8, 14, 20, 26, 32),
 (1, 7, 13, 19, 25, 31),
 (0, 6, 12, 18, 24, 30)]